// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpukuaxhcwsvqytiazfp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwdWt1YXhoY3dzdnF5dGlhemZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDI2MTAsImV4cCI6MjA3NDQ3ODYxMH0.igfpjOCqMRApGqg3skk9WzJ7fZd-e1BdOY9t4__JE0U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});